/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e42a83ca5e1dccc4c80b5647838a28b)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	SITE_URL: "https://lovenote.example.com";
	R2_ACCOUNT_ID: "replace-with-cloudflare-account-id";
	R2_BUCKET_NAME: "lovenote-media";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME">> {}
}
