/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0c459e7aac1462de8108f32bb80ab612)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	SITE_URL: "http://127.0.0.1:4321" | "https://lovenote.example.com";
	R2_ACCOUNT_ID: "0de76f4cb5141aec57087740b58a590f";
	R2_BUCKET_NAME: "lovenote-media-test" | "lovenote-media";
	DATABASE_URL: string;
	BETTER_AUTH_SECRET: string;
	SETUP_SECRET: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface AcceptanceEnv {
		MEDIA_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		SITE_URL: "http://127.0.0.1:4321";
		R2_ACCOUNT_ID: "0de76f4cb5141aec57087740b58a590f";
		R2_BUCKET_NAME: "lovenote-media-test";
		DATABASE_URL: string;
		BETTER_AUTH_SECRET: string;
		SETUP_SECRET: string;
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "DATABASE_URL" | "BETTER_AUTH_SECRET" | "SETUP_SECRET" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY">> {}
}
